export const tournaments = [
  {
    id: 'tft',
    name: 'Teamfight Tactics',
    cashprize: 1600,
    maxPlayers: 80,
    playersPerTeam: 5,
    image: 'https://arena.utt.fr/tournaments/tft.jpg',
    backgroundImage: 'https://arena.utt.fr/tournaments/tft.jpg',
    caster: 'Caster1',
    enrolledTeams: 13,
  },
  {
    id: 'csgo',
    name: 'Counter-Strike: Global Offsensive',
    cashprize: 1600,
    maxPlayers: 80,
    playersPerTeam: 5,
    image: 'https://arena.utt.fr/tournaments/csgo.jpg',
    backgroundImage: '/images/tournaments/csgo-background.png',
    caster: 'Caster2',
    enrolledTeams: 10,
  },
  {
    id: 'tft1',
    name: 'Teamfight Tactics',
    cashprize: 1600,
    maxPlayers: 80,
    playersPerTeam: 5,
    image: 'https://arena.utt.fr/tournaments/tft.jpg',
    backgroundImage: 'https://arena.utt.fr/tournaments/tft.jpg',
    caster: 'Caster1',
    enrolledTeams: 13,
  },
  {
    id: 'csgo1',
    name: 'Counter-Strike: Global Offsensive',
    cashprize: 1600,
    maxPlayers: 80,
    playersPerTeam: 5,
    image: 'https://arena.utt.fr/tournaments/csgo.jpg',
    backgroundImage: '/images/tournaments/csgo-background.png',
    caster: 'Caster2',
    enrolledTeams: 10,
  },
  {
    id: 'tft2',
    name: 'Teamfight Tactics',
    cashprize: 1600,
    maxPlayers: 80,
    playersPerTeam: 5,
    image: 'https://arena.utt.fr/tournaments/tft.jpg',
    backgroundImage: 'https://arena.utt.fr/tournaments/tft.jpg',
    caster: 'Caster1',
    enrolledTeams: 13,
  },
  {
    id: 'csgo2',
    name: 'Counter-Strike: Global Offsensive',
    cashprize: 1600,
    maxPlayers: 80,
    playersPerTeam: 5,
    image: 'https://arena.utt.fr/tournaments/csgo.jpg',
    backgroundImage: '/images/tournaments/csgo-background.png',
    caster: 'Caster2',
    enrolledTeams: 10,
  },
  {
    id: 'tft3',
    name: 'Teamfight Tactics',
    cashprize: 1600,
    maxPlayers: 80,
    playersPerTeam: 5,
    image: 'https://arena.utt.fr/tournaments/tft.jpg',
    backgroundImage: 'https://arena.utt.fr/tournaments/tft.jpg',
    caster: 'Caster1',
    enrolledTeams: 13,
  },
  {
    id: 'csgo3',
    name: 'Counter-Strike: Global Offsensive',
    cashprize: 1600,
    maxPlayers: 80,
    playersPerTeam: 5,
    image: 'https://arena.utt.fr/tournaments/csgo.jpg',
    backgroundImage: '/images/tournaments/csgo-background.png',
    caster: 'Caster2',
    enrolledTeams: 10,
  },
];
