export default {
  catchPhrase: 'Les 7 tournois à l\'UTT Arena 2019',
  list: [
    {
      title: 'League of Legends (Pro)',
      rewards: '1700€ et lots',
      players: 80,
      img: '/static/lolpro.webp',
      link: '/tournaments/lol-pro',
      id: 1,
    },
    {
      title: 'League of Legends (Amateur)',
      rewards: 'lots',
      players: 80,
      img: '/static/lolamateur.webp',
      link: '/tournaments/lol-amateur',
      id: 2,
    },
    {
      title: 'Super Smash Bros Ultimate',
      rewards: '650€ et lots',
      players: 64,
      img: '/static/ssbu.webp',
      link: '/tournaments/ssbu',
      id: 5,
    },
    {
      title: 'Counter-Strike : Global Offensive',
      rewards: '1450€ et lots',
      players: 80,
      img: '/static/csgo.webp',
      link: '/tournaments/csgo',
      id: 4,
    },
    {
      title: 'Fortnite',
      rewards: '1200€ et lots',
      players: 96,
      img: '/static/fortnite.webp',
      link: '/tournaments/fortnite',
      id: 3,
    },
    {
      title: 'osu!',
      players: 24,
      img: '/static/osu.webp',
      link: '/tournaments/osu',
      id: 6,
    },
    {
      title: 'Libre',
      players: 24,
      img: '/static/libre.webp',
      link: '/tournaments/libre',
      id: 7,
    },
  ],
};