export default {
  catchPhrase: "Les 7 tournois à l'UTT Arena 2019",
  list: [
    {
      title: 'League of Legends (Pro)',
      rewards: '1700€ et lots',
      players: 80,
      image: '/assets/lolpro.png',
      link: '/tournaments/lol-pro',
      id: 1,
    },
    {
      title: 'League of Legends (Amateur)',
      rewards: 'lots',
      players: 80,
      image: '/assets/lolamateur.png',
      link: '/tournaments/lol-amateur',
      id: 2,
    },
    {
      title: 'Super Smash Bros Ultimate',
      rewards: '650€ et lots',
      players: 64,
      image: '/assets/ssbu.png',
      link: '/tournaments/ssbu',
      id: 5,
    },
    {
      title: 'Counter-Strike : Global Offensive',
      rewards: '1450€ et lots',
      players: 80,
      image: '/assets/csgo.png',
      link: '/tournaments/csgo',
      id: 4,
    },
    {
      title: 'Fortnite',
      rewards: '1200€ et lots',
      players: 96,
      image: '/assets/fortnite.png',
      link: '/tournaments/fortnite',
      id: 3,
    },
    {
      title: 'osu!',
      players: 24,
      image: '/assets/osu.png',
      link: '/tournaments/osu',
      id: 6,
    },
    {
      title: 'Libre',
      players: 24,
      image: '/assets/libre.png',
      link: '/tournaments/libre',
      id: 7,
    },
  ],
};
